### ISSUE TITLE
Update package on npm?

### ISSUE THREAD

**Issue by aarondack** [hyspace/grunt-jinja2#8]
Hey guys,

Any thoughts on pushing a new package to npm? 

`npm install grunt-jinja2` does not have the `global_context_file` option that I'm sure people would like to use (I'm one of them 😀).

**Comment by dgarana** [comment]
Same issue here

**Comment by dgarana** [comment]
Just deployed a new version of it under: `npm install grunt-jinja2-redux`

**Comment by aarondack** [comment]
Nice!
